from __future__ import annotations

import re
import uuid
from datetime import UTC, datetime
from typing import Any

from . import errors
from .config import Settings

_INCIDENT_ID_RE = re.compile(r"[A-Za-z0-9_-]{1,64}")


def save_report(
    settings: Settings, incident_id: str, job_ids: list[str], markdown: str
) -> dict[str, Any]:
    """Write a Claude-authored report to a code-generated path under OUTPUT.

    Never accepts a path from the caller (guide section 10: "never accept an
    arbitrary output path"), and never overwrites a prior report — each save
    gets its own timestamped filename, so every earlier report and the
    source evidence stay intact. The result is explicitly labelled
    Claude-authored and not mechanically verified: saving text does not
    check whether its citations are accurate (guide section 10).
    """
    config_error = settings.evidence_config_error()
    if config_error:
        raise errors.config_invalid(config_error)
    assert settings.output is not None
    if not _INCIDENT_ID_RE.fullmatch(incident_id):
        raise errors.incident_not_found(incident_id)

    reports_dir = settings.output / "reports" / incident_id
    if not reports_dir.resolve().is_relative_to(settings.output.resolve()):
        raise errors.path_rejected(incident_id)
    reports_dir.mkdir(parents=True, exist_ok=True)

    saved_at = datetime.now(UTC)
    filename = f"report-{saved_at.strftime('%Y%m%dT%H%M%S%f')}Z-{uuid.uuid4().hex[:8]}.md"
    path = reports_dir / filename

    header = (
        "<!-- Generated by Claude via sap-incident-lab. Not mechanically verified —\n"
        "     verify citations against incident_lab_get_evidence before relying on them. -->\n"
        f"<!-- incident_id: {incident_id} -->\n"
        f"<!-- job_ids: {', '.join(job_ids)} -->\n"
        f"<!-- saved_at: {saved_at.isoformat()} -->\n\n"
    )
    with path.open("x", encoding="utf-8") as report:
        report.write(header + markdown)

    return {
        "incident_id": incident_id,
        "job_ids": job_ids,
        "path": str(path.relative_to(settings.output)),
        "saved_at": saved_at.isoformat(),
        "claude_authored": True,
        "mechanically_verified": False,
    }
