from __future__ import annotations

import re
import uuid
from datetime import UTC, datetime
from importlib.metadata import version
from typing import Any

from . import errors
from .config import Settings

_INCIDENT_ID_RE = re.compile(r"[A-Za-z0-9_-]{1,64}")


def save_report(
    settings: Settings, incident_id: str, job_ids: list[str], markdown: str
) -> dict[str, Any]:
    """Write a Claude-authored report to a code-generated path under OUTPUT.

    Never accepts a path from the caller (guide section 10: "never accept an
    arbitrary output path"), and never overwrites a prior report — each save
    gets its own timestamped filename, so every earlier report and the
    source evidence stay intact. The result is explicitly labelled
    Claude-authored and not mechanically verified: saving text does not
    check whether its citations are accurate (guide section 10).
    """
    config_error = settings.evidence_config_error()
    if config_error:
        raise errors.config_invalid(config_error)
    assert settings.output is not None
    if not _INCIDENT_ID_RE.fullmatch(incident_id):
        raise errors.incident_not_found(incident_id)

    reports_dir = settings.output / "reports" / incident_id
    if not reports_dir.resolve().is_relative_to(settings.output.resolve()):
        raise errors.path_rejected(incident_id)
    reports_dir.mkdir(parents=True, exist_ok=True)

    saved_at = datetime.now(UTC)
    filename = f"report-{saved_at.strftime('%Y%m%dT%H%M%S%f')}Z-{uuid.uuid4().hex[:8]}.md"
    path = reports_dir / filename

    header = (
        "<!-- Generated by Claude via sap-incident-lab. Not mechanically verified —\n"
        "     verify citations against incident_lab_get_evidence before relying on them. -->\n"
        f"<!-- incident_id: {incident_id} -->\n"
        f"<!-- job_ids: {', '.join(job_ids)} -->\n"
        f"<!-- saved_at: {saved_at.isoformat()} -->\n\n"
        f"<!-- app_version: {version('sap-incident-lab')} -->\n\n"
    )
    with path.open("x", encoding="utf-8") as report:
        report.write(header + markdown)

    return {
        "incident_id": incident_id,
        "job_ids": job_ids,
        "path": str(path.relative_to(settings.output)),
        "saved_at": saved_at.isoformat(),
        "claude_authored": True,
        "mechanically_verified": False,
    }


def report_template(settings: Settings, incident_id: str, job_ids: list[str]) -> dict[str, Any]:
    from .analysis.workflow import progress
    from .evidence.registry import load_files
    from .jobs.store import JobStore

    manifest, records = load_files(settings, incident_id)
    assert settings.output is not None
    store = JobStore(settings.output)
    jobs = []
    for job_id in dict.fromkeys(job_ids):
        job = store.load(job_id)
        if job is None:
            raise errors.job_not_found(job_id)
        if job.incident_id != incident_id:
            raise errors.ToolError("JOB_INCIDENT_MISMATCH", "The job belongs to a different incident.",
                                   "Use only job IDs from the report incident.")
        jobs.append(job)
    # Deliberately leave conclusions blank; a template cannot verify model claims.
    lines = [
        f"# Incident report: {incident_id}", "",
        "Draft; keep this report concise. Claims and citations require human review.", "",
        "## Summary", "", "[Impact and one-sentence incident summary. Separate facts from inference.]", "",
        "## Scope and coverage", "",
    ]
    if not jobs:
        lines.append("No analysis jobs selected; analysis coverage has not been established.")
    for job in jobs:
        detail = progress(store, job)
        lines.append(f"- {job.job_id} ({job.state}): {detail['summary']} Primary model {job.model}; attempt {job.attempts}.")
        for file_id, sha256 in job.file_hashes.items():
            current = next((r.sha256 for r in records if r.file_id == file_id), None)
            if current != sha256:
                lines.append(f"  SOURCE CHANGED: {file_id}; job hash {sha256}. Reinvestigate before citing current lines.")
    lines += ["", f"Application version: {version('sap-incident-lab')}.",
              f"Configured fallback model: {settings.fallback_model or 'none'}."]
    lines += ["", "Coverage is per job; do not add overlapping jobs. Extraction is not a verified root cause.", "",
              "## Evidence inventory", ""]
    for record in records:
        name = record.rel_path.replace("\n", " ").replace("\r", " ").replace("`", "'")
        lines.append(f"- {record.file_id} {name} ({record.line_count} lines; SHA-256 {record.sha256}).")
    lines += [
        "", "## Findings and evidence", "",
        "[Use short bullets. Cite file ID, exact line range and SHA-256 from incident_lab_get_evidence.]",
        "", "## Hypotheses", "",
        "[List only the top hypotheses, each with supporting evidence and one discriminating check.]",
        "", "## Missing information", "",
        f"[Key gaps only.] SID: {manifest.system.sid or 'unknown'}; timezone: {manifest.time_window.timezone or 'unknown'}.",
        "", "## Next checks", "", "[Prioritized checks only; include owner/outcome when useful.]",
        "", "## Limitations", "",
        "[State failed, pending, skipped, changed-source, and unverified items in one short bullet list.]", "",
    ]
    return {"incident_id": incident_id, "job_ids": list(dict.fromkeys(job_ids)),
            "markdown": "\n".join(lines), "mechanically_verified": False}


def list_reports(settings: Settings, incident_id: str) -> dict[str, Any]:
    """List saved reports without exposing arbitrary filesystem paths."""
    if settings.evidence_config_error():
        raise errors.config_invalid(settings.evidence_config_error() or "invalid configuration")
    if not _INCIDENT_ID_RE.fullmatch(incident_id):
        raise errors.incident_not_found(incident_id)
    assert settings.output is not None
    reports_dir = settings.output / "reports" / incident_id
    if not reports_dir.resolve().is_relative_to(settings.output.resolve()):
        raise errors.path_rejected(incident_id)
    reports = []
    if reports_dir.is_dir():
        for path in sorted(reports_dir.glob("report-*.md"), reverse=True):
            if path.is_file():
                reports.append({
                    "filename": path.name,
                    "path": str(path.relative_to(settings.output)),
                    "size_bytes": path.stat().st_size,
                    "modified_at": datetime.fromtimestamp(path.stat().st_mtime, UTC).isoformat(),
                })
    return {"incident_id": incident_id, "reports": reports}
